[project]
name = "pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "ipython>=9.7.0",
    "polars>=1.35.2",
    "psycopg>=3.3.0",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.44",
]
